export enum ApiEndpoints {
    EmailSendWelcome = 'http://localhost:8000/api/send-welcome-email',
    EmailSendOTP = 'http://localhost:8000/api/send-otp-email',
    UserGetData = 'http://localhost:8000/api/user',
    UserRegister = 'http://localhost:8000/api/register',
    UserLogin = 'http://localhost:8000/api/login',
    UserLoginOTP = 'http://localhost:8000/api/login-otp',
    UserLogout = 'http://localhost:8000/api/logout',
    GeoGuesser = 'http://localhost:5000/geoguesser-guess',
    UserValidateEmail = 'http://localhost:8000/api/validate-reset-password-email',
    AirportSearch = 'http://localhost:8000/api/search-airports',
    PromoCreate = 'http://localhost:8000/api/create-promo',
    UserGetPromos = 'http://localhost:8000/api/get-user-promos',
    PromosGetAllData = 'http://localhost:8000/api/get-all-promos',
    UserGetAllData = 'http://localhost:8000/api/get-all-users',
    FlightRouteSearch = 'http://localhost:8000/api/get-flight-routes',
    AirlineFromRoutes = 'http://localhost:8000/api/get-airline-from-routes',
    AvailableAirplanesFromAirline = 'http://localhost:8000/api/get-available-airplane',
    CreateFlight = 'http://localhost:8000/api/create-flight',
    FlightsPendingGetAllData = 'http://localhost:8000/api/get-all-pending-flights',
    FlightsPendingSearchFromLocation = 'http://localhost:8000/api/get-flights-from-location',
    FlightGetDetails = 'http://localhost:8000/api/get-flight-details',
    CityGetData = 'http://localhost:8000/api/get-city',
    AirportGetData = 'http://localhost:8000/api/get-airport',
    SeatGetDetail = 'http://localhost:8000/api/get-seat-details',
    SeatGetAmount = 'http://localhost:8000/api/get-seat-amount',
    FlightCompleteTransactionCreate = 'http://localhost:8000/api/create-complete-flight-transaction',
    HotelCompleteTransactionCreate = 'http://localhost:8000/api/create-complete-hotel-transaction',
    // User = 'http://localhost:8000/api/:ID/ban',
    // UserTransactionCreate = 'http://localhost:8000/api/create-user-transaction',
    // FlightTransactionCreate = 'http://localhost:8000/api/create-flight-transaction',
    // TravelerCreate = 'http://localhost:8000/api/create-traveler',
    HotelCreate = 'http://localhost:8000/api/create-hotel',
    HotelGetAllData = 'http://localhost:8000/api/get-all-hotels',
    HotelRoomDetailsCreate = 'http://localhost:8000/api/create-room-details',
    HotelRoomDetailsGetData = 'http://localhost:8000/api/get-hotel-and-room-details',
    UserUpdateProfile = 'http://localhost:8000/api/update-user-profile',
    UpdatePassword = 'http://localhost:8000/api/update-password',
    UpdateHotelTime = 'http://localhost:8000/api/update-hotel-time',
    GetCart = 'http://localhost:8000/api/get-cart',
    UpdatePromo = 'http://localhost:8000/api/update-promo',
    UserCCUpdateOrCreate = 'http://localhost:8000/api/user/cc',
    SearchCities = 'http://localhost:8000/api/search-cities',
    HotelPay = 'http://localhost:8000/api/hotel-pay',
    


}

export const BanUser = (userId:number) => `http://localhost:8000/api/user/${userId}/ban`